### ISSUE TITLE
Next episode doesn't play automatically (Jellyfin)

### ISSUE THREAD

**Issue by fl380** [MoojMidge/service.upnext#15]
Hello, sorry to bother you again.
Upnext detects the next episode but doesn't play it automatically - I suspect that it is related to the previous issue?
 
[kodi.log](https://github.com/MoojMidge/service.upnext/files/10303181/kodi.log)

**Comment by MoojMidge** [comment]
All good. Not related to the previous issues, this is just a bug I introduced a little while back.

What's interesting is that the three different issues you raised, and the logs provided, show Jellyfin playing videos and integrating with UpNext in three different ways.

Not sure why Jellyfin does this, but I missed this particular integration method when fixing the other two issues that used different playback methods, so it serves as a good test case.

Should be fixed by https://github.com/MoojMidge/service.upnext/commit/8cd2ce523db33a717ce6143e6b366ad2037eb618. Can you download latest from master and confirm?

**Comment by fl380** [comment]
That seems to have works, thanks.
[kodi.log](https://github.com/MoojMidge/service.upnext/files/10308739/kodi.log)
