### ISSUE TITLE
Still watching behavior 

### ISSUE THREAD

**Issue by booyakafoo** [MoojMidge/service.upnext#28]
Wondering if you might consider a couple changes in the Still Watching behavior?

Currently "Close" on still watching popup will stop playback instead of just closing the popup.  Can you modify so it will just close the popup and let the playback continue till the end of the episode?
And
Would you consider a double response for the still watching prompt. 

Still watching, YES  
Don't click and playback stops.  Click yes and you are presented with the normal up next prompt, to watch next or close.  

If you want a use case.  I have the popup timer set to 160 seconds.  I've had many times where I get to a still watching prompt and want to just press continue and let the playback go on but I have to wait for the credits to press continue since the next episode starts after the press. 

For the close button. I don't think it should stop playback unless the user changed the settings for show a stop.  

Thanks as always.

**Comment by MoojMidge** [comment]
> Currently "Close" on still watching popup will stop playback instead of just closing the popup. Can you modify so it will just close the popup and let the playback continue till the end of the episode?

Not possible unfortunately. Well it is, but it can cause issues when fast forwarding, skipping, or if the popup doesn't fully close before the playback event of next item is fired, which will result in the next item playing, even if a user did, or was intending to, click Close/Stop.

It can also happen on an Up Next popup, but in that instance it is generally OK, since that is (usually) the desired action anyway.

As a compromise to putting in this workaround, there was meant to be a secondary method to close the popup - by pressing `Esc` or `Back' on your keyboard or remote. However, looking at the code it looks like I removed this for some reason. Can't remember why.

You can add it back in and see if that works for you. If it does then I will add it back in permanently. 

Change this line:
https://github.com/MoojMidge/service.upnext/blob/7de9a3756cc2a3ec37f3f92758cd529fc6be66b4/resources/lib/popuphandler.py#L228C65-L228C65

To:
```
            popup_state['show_upnext'] or self._sigcont.is_set() or popup_state['cancel']
```

> If you want a use case. I have the popup timer set to 160 seconds. I've had many times where I get to a still watching prompt and want to just press continue and let the playback go on but I have to wait for the credits to press continue since the next episode starts after the press.

Don't quite understand. If you press continue and then another popup appears won't you need to then press play or just wait again for this new popup? It's the same as the original isn't it? 

> For the close button. I don't think it should stop playback unless the user changed the settings for show a stop.
> 
> Thanks as always.

No problem. Yeah, it would be ideal if the close button worked reliably, but sometimes Kodi doesn't do what you think it will. See how you go with the Back command instead

**Comment by booyakafoo** [comment]
I may have a slight mental problem because all of this stems from me not wanting to stop an episode before the credits are started but also not wanting to pay attention to the TV to wait for the credits to start. lol 

Adding the back button code works perfectly for me.  I usually leave the TV on when I work or I'm on my phone not paying attention to the TV and know that by the end of the 3rd episode in a row, I need to interact with the playback to keep it going.  The interaction I would prefer be simple like pressing back does now and I can go back to what I was working on and the playback continues.  Where before, on the 3rd episode I would have to wait for it to get to the credits or press next and miss some of the episode.  Again this is a personal issue since a normal person would actually watch the show that's on or just hit next and might not care that the episode wasn't completely over.  

Hope that makes sense and thanks for the other option!

**Comment by MoojMidge** [comment]
LOL... the only reason I do any of this with Kodi is because it doesn't quite do what I want it to and it bothered me enough that I decided to learn Python.

To be clear do you still need/want something different to happen when you hit Continue on the Still Watching popup?

**Comment by booyakafoo** [comment]
I really appreciate it.  This addon is probably my most used and really ties my setup together.  I don't need anything else right now.
